name: C CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build and Run Main
      run: |
        gcc -Wall -o main main.c lib_ppm.c
        ./main